config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :myfriends
  get 'home/index'
  get 'home/about'
  root 'myfriends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myfriend.rb
class Myfriend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :myfriends

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
    @about_me = "My Name is Samuel Jeon!"
    @answer = 2+2
  end
end

app/controllers/myfriends_controller.rb
class MyfriendsController < ApplicationController
  before_action :set_myfriend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /myfriends or /myfriends.json
  def index
    @myfriends = Myfriend.all

  end

  # GET /myfriends/1 or /myfriends/1.json
  def show
  end

  # GET /myfriends/new
  def new
    #@myfriend = Myfriend.new
    @myfriend = current_user.myfriends.build
  end

  # GET /myfriends/1/edit
  def edit
  end

  # POST /myfriends or /myfriends.json
  def create
    #@myfriend = Myfriend.new(myfriend_params)
    @myfriend = current_user.myfriends.build(myfriend_params)
    respond_to do |format|
      if @myfriend.save
        format.html { redirect_to myfriend_url(@myfriend), notice: "Myfriend was successfully created." }
        format.json { render :show, status: :created, location: @myfriend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @myfriend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myfriends/1 or /myfriends/1.json
  def update
    respond_to do |format|
      if @myfriend.update(myfriend_params)
        format.html { redirect_to myfriend_url(@myfriend), notice: "Myfriend was successfully updated." }
        format.json { render :show, status: :ok, location: @myfriend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @myfriend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myfriends/1 or /myfriends/1.json
  def destroy
    @myfriend.destroy

    respond_to do |format|
      format.html { redirect_to myfriends_url, notice: "Myfriend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  
  def correct_user
    @myfriend = current_user.myfriends.find_by(id: params[:id])
    redirect_to myfriends_path, notice: "Not Authorized To Edit This Friend" if @myfriend.nil?
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myfriend
      @myfriend = Myfriend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def myfriend_params
      params.require(:myfriend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/myfriends_helper.rb
module MyfriendsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'My First App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>

        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_myfriend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
        
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        
        
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>about us...</h1>

<p>
    
    <%= @about_me %>
    
</p>

<p> 2 + 2 = <%= @answer%></p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first Rails webpage!

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice%>  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "home/header"%>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      </br>
      <%= yield %>
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/myfriends/_form.html.erb
<%= form_with(model: myfriend, local: true) do |form| %>
  <% if myfriend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(myfriend.errors.count, "error") %> prohibited this myfriend from being saved:</h2>

      <ul>
        <% myfriend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter"%>
  </div>
  <br/>
   <div class="field form-group">
    <%= form.number_field :user_id, id: :myfriend_user_id, class:"form-control", value: current_user.id, type:"hidden" %>
  </div>
<br/>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/myfriends/edit.html.erb
<h1>Editing Myfriend</h1>

<%= render 'form', myfriend: @myfriend %>
<br/>
<%= link_to 'Show', @myfriend, class:"btn btn-secondary" %>
<%= link_to 'Delete', @myfriend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>
<%= link_to 'Back', myfriends_path, class:"btn btn-secondary"  %>

app/views/myfriends/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-primary text-center" style="width: 100%">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th> </th>
    </tr>
  </thead>

  <tbody class="text-center" style="width: 100%">
    <% @myfriends.each do |myfriend| %>
    <% if myfriend.user == current_user %>
      <tr>
        <td ><%= link_to myfriend.first_name + " " + myfriend.last_name, myfriend, style:"text-decoration:none" %>
          </td>
        <td><%= myfriend.email %></td>
        <td><%= myfriend.phone %></td>
        <td><%= myfriend.twitter %></td>

          <td><%= link_to 'Delete', myfriend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm", style:"width: 100%" %></td>

      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My friend', new_myfriend_path, class: "btn btn-secondary" %>
<% else %>
<h1>Hello World!</h1>
This is my first Rails webpage!


<% end %>

app/views/myfriends/new.html.erb
<h1>Add New Myfriend</h1>
<br/>
<%= render 'form', myfriend: @myfriend %>
<br/>
<%= link_to 'Back', myfriends_path, class:"btn btn-dark" %>

app/views/myfriends/show.html.erb
<div style="margin-top:55px; padding-top:55px;" class="container-fluid text-sm-center p-5 bg-info text-white "> <!-- bg-light is background color & p-5 is padding -->
    <h1 class="display-2">  <%= @myfriend.first_name %>   <%= @myfriend.last_name %></h1>
    <p class="lead">
      <%= @myfriend.email %>  |
      <%= @myfriend.phone %>  |
      <%= @myfriend.twitter %>
    </p>
    <br/>
<%= link_to 'Edit', edit_myfriend_path(@myfriend), class:"btn btn-secondary" %>
<%= link_to 'Delete', @myfriend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"%>

<%= link_to 'Back', myfriends_path,class:"btn btn-dark" %>
</div>